docker:
  engine:
    version: "20.10.22"
    config:
      storage_driver: "overlay2"
      log_driver: "json-file"
      log_opts:
        max_size: "100m"
      exec_opts:
        - "native.cgroupdriver=systemd"

  compose:
    version: "v2.12.2"
  
  params_file:
    config_path: "/etc/docker/daemon.json"
    compose_path: "/usr/local/bin/docker-compose"
